"""
Compute Component 1 — CLC (Corporate Landlord Concentration).

CLC_tract = Σ(REIT-owned units in tract) / ACS B25003 renter_occupied

Steps
─────
1. Load communities_with_acs_{year}.csv
2. Filter to properties in the 10 target metro counties
3. Cross-year imputation: for each property missing unit_count in its most-recent
   filing year, fill from any earlier year's unit_count for the same property
4. Dedup to most-recent filing year per property
5. Aggregate REIT unit counts to census-tract level
6. Divide by ACS renter_occupied → CLC ratio
7. Write data/processed/c1_clc_{year}.csv

Usage:
    python src/compute_c1_clc.py [--year 2022]
"""

import argparse
import csv
from collections import defaultdict
from pathlib import Path
from typing import Optional

# ---------------------------------------------------------------------------
# Metro → county FIPS mapping
# ---------------------------------------------------------------------------

METRO_COUNTIES = {
    "Los Angeles":       ["06037", "06059"],
    "New York":          ["36061", "36047", "36081", "36005", "36085",
                          "36059", "36103", "36119",
                          "34003", "34013", "34017", "34019", "34023",
                          "34025", "34029", "34035", "34039"],
    "Seattle":           ["53033", "53053", "53061"],
    "San Francisco":     ["06001", "06013", "06041", "06075", "06081"],
    "Washington DC":     ["11001", "51013", "51510", "51059", "51153",
                          "51179", "24031", "24033"],
    "Dallas-Fort Worth": ["48113", "48085", "48121", "48139", "48251", "48439"],
    "San Jose":          ["06085"],
    "San Diego":         ["06073"],
    "Atlanta":           ["13121", "13135", "13089", "13067", "13063",
                          "13057", "13151"],
    "Charlotte":         ["37119", "37025", "37179", "37071", "37097"],
}

COUNTY_TO_METRO = {
    county: metro
    for metro, counties in METRO_COUNTIES.items()
    for county in counties
}

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

BASE_DIR      = Path(__file__).parent.parent
PROCESSED_DIR = BASE_DIR / "data" / "processed"

OUTPUT_FIELDS = [
    "metro",
    "census_tract_geoid",
    "county_fips",
    "state_fips",
    "reit_units_total",
    "reit_units_imputed_count",
    "num_reit_properties",
    "tickers_present",
    "acs_renter_occupied",
    "clc",
    "acs_year",
]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def parse_args():
    p = argparse.ArgumentParser(description="Compute AHBI Component 1: CLC")
    p.add_argument("--year", type=int, default=2022,
                   help="ACS vintage year (default: 2022)")
    p.add_argument("--min-renter-occupied", type=int, default=None,
                   help="Drop tracts where 2018 renter_occupied < this value. "
                        "Saves excluded GEOIDs to clc_excluded_tracts.txt for use "
                        "with --exclude-geoids in other years.")
    p.add_argument("--exclude-geoids", action="store_true",
                   help="Load and apply clc_excluded_tracts.txt (generated by "
                        "--min-renter-occupied on the 2018 run).")
    return p.parse_args()


def full_fips(row) -> str:
    return row.get("state_fips", "") + row.get("county_fips", "")


def to_float(val) -> Optional[float]:
    try:
        f = float(val)
        return None if f < 0 else f
    except (TypeError, ValueError):
        return None


def safe_div(num, den) -> str:
    if num is None or den is None or den == 0:
        return ""
    return f"{num / den:.6f}"


def prop_key(row) -> tuple:
    return (
        row.get("community_name", "").lower().strip(),
        row.get("city", "").lower().strip(),
        row.get("state", "").lower().strip(),
    )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    args       = parse_args()
    year       = args.year
    input_file = PROCESSED_DIR / f"communities_with_acs_{year}.csv"
    out_file   = PROCESSED_DIR / f"c1_clc_{year}.csv"

    if not input_file.exists():
        raise SystemExit(
            f"{input_file.name} not found.\n"
            f"Run: python src/get_acs_data.py --year {year}"
        )

    all_rows = list(csv.DictReader(open(input_file, newline="", encoding="utf-8")))
    print(f"Loaded {len(all_rows):,} rows from {input_file.name}")

    # ── 1. Filter to metro counties ──────────────────────────────────────────
    metro_rows = [r for r in all_rows if COUNTY_TO_METRO.get(full_fips(r))]
    for r in metro_rows:
        r["metro"] = COUNTY_TO_METRO[full_fips(r)]
    print(f"In target metros: {len(metro_rows):,} rows "
          f"({len(all_rows) - len(metro_rows):,} outside metros dropped)")

    # ── 2. Cross-year imputation lookup ──────────────────────────────────────
    # For each property key, collect all (filing_year, unit_count) pairs across
    # all years in the file, then pick the most-recent non-null value.
    prop_units_by_year: dict[tuple, list] = defaultdict(list)
    for r in metro_rows:
        uc = r.get("unit_count", "").strip()
        if uc:
            prop_units_by_year[prop_key(r)].append((r.get("filing_year", ""), uc))

    best_unit: dict[tuple, str] = {}
    for key, pairs in prop_units_by_year.items():
        pairs.sort(key=lambda x: x[0], reverse=True)
        best_unit[key] = pairs[0][1]

    # ── 3. Dedup to most-recent filing year ≤ ACS year per property ──────────
    # Cap at the ACS year so numerator (REIT units) and denominator (ACS
    # renter_occupied) reflect the same time period.  A 2022 filing should
    # not contribute to the 2018 CLC, since those units may not have existed.
    latest: dict = {}
    for r in metro_rows:
        if r.get("filing_year", "") > str(year):
            continue   # filing is after the ACS vintage — skip
        key = prop_key(r)
        if key not in latest or r["filing_year"] > latest[key]["filing_year"]:
            latest[key] = r

    deduped = list(latest.values())
    print(f"After dedup (most-recent year per property): {len(deduped):,} unique properties")

    # Fill missing unit_counts from imputation lookup
    imputed_count = 0
    still_missing = 0
    patched = []
    for r in deduped:
        uc = r.get("unit_count", "").strip()
        if not uc:
            key = prop_key(r)
            if key in best_unit:
                r = dict(r)
                r["unit_count"] = best_unit[key]
                r["_imputed"] = True
                imputed_count += 1
            else:
                r = dict(r)
                r["_imputed"] = False
                still_missing += 1
        else:
            r = dict(r)
            r["_imputed"] = False
        patched.append(r)

    print(f"  Unit count imputed from earlier year: {imputed_count}")
    print(f"  Still missing after imputation:       {still_missing}")

    # ── 4. Aggregate to tract level ───────────────────────────────────────────
    tract_units:    dict[str, float] = defaultdict(float)
    tract_imputed:  dict[str, int]   = defaultdict(int)
    tract_props:    dict[str, int]   = defaultdict(int)
    tract_tickers:  dict[str, set]   = defaultdict(set)
    tract_meta:     dict[str, dict]  = {}

    for r in patched:
        geoid = r.get("census_tract_geoid", "")
        if not geoid:
            continue

        units = to_float(r.get("unit_count"))
        if units:
            tract_units[geoid] += units
            if r.get("_imputed"):
                tract_imputed[geoid] += 1

        tract_props[geoid]  += 1
        tract_tickers[geoid].add(r.get("ticker", ""))

        if geoid not in tract_meta:
            tract_meta[geoid] = {
                "metro":               r.get("metro", ""),
                "census_tract_geoid":  geoid,
                "county_fips":         r.get("county_fips", ""),
                "state_fips":          r.get("state_fips", ""),
                "acs_renter_occupied": r.get("renter_occupied", ""),
                "acs_year":            r.get("acs_year", ""),
            }

    # ── 5. Compute CLC ────────────────────────────────────────────────────────
    rows_out = []
    for geoid, meta in sorted(tract_meta.items()):
        reit_units      = tract_units.get(geoid, 0.0)
        renter_occupied = to_float(meta["acs_renter_occupied"])
        clc             = safe_div(reit_units, renter_occupied)

        rows_out.append({
            "metro":                    meta["metro"],
            "census_tract_geoid":       geoid,
            "county_fips":              meta["county_fips"],
            "state_fips":               meta["state_fips"],
            "reit_units_total":         reit_units if reit_units else "",
            "reit_units_imputed_count": tract_imputed.get(geoid, 0),
            "num_reit_properties":      tract_props.get(geoid, ""),
            "tickers_present":          "|".join(sorted(tract_tickers.get(geoid, set()))),
            "acs_renter_occupied":      meta["acs_renter_occupied"],
            "clc":                      clc,
            "acs_year":                 meta["acs_year"],
        })

    # ── 6. Apply exclusions ───────────────────────────────────────────────────
    exclusion_file = PROCESSED_DIR / "clc_excluded_tracts.txt"

    if args.min_renter_occupied and year == 2018:
        # Identify tracts below the renter_occupied floor in the 2018 ACS
        threshold = args.min_renter_occupied
        excluded = {
            r["census_tract_geoid"]
            for r in rows_out
            if to_float(r["acs_renter_occupied"]) is not None
            and to_float(r["acs_renter_occupied"]) < threshold
        }
        rows_out = [r for r in rows_out if r["census_tract_geoid"] not in excluded]
        # Save exclusion list for use in other years
        exclusion_file.write_text("\n".join(sorted(excluded)), encoding="utf-8")
        print(f"\nExcluded {len(excluded)} tracts (renter_occupied < {threshold} in 2018 ACS)")
        print(f"Exclusion list saved → {exclusion_file.name}")

    elif args.exclude_geoids:
        if not exclusion_file.exists():
            raise SystemExit(
                f"{exclusion_file.name} not found.\n"
                "Run for 2018 first with --min-renter-occupied 150 to generate it."
            )
        excluded = set(exclusion_file.read_text(encoding="utf-8").splitlines())
        rows_out = [r for r in rows_out if r["census_tract_geoid"] not in excluded]
        print(f"\nApplied exclusion list: dropped {len(excluded)} tracts → {exclusion_file.name}")

    # ── 7. Write output ───────────────────────────────────────────────────────
    with open(out_file, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=OUTPUT_FIELDS)
        writer.writeheader()
        writer.writerows(rows_out)

    # ── Summary ───────────────────────────────────────────────────────────────
    valid_clc = [float(r["clc"]) for r in rows_out if r["clc"]]
    print(f"\n{'─'*50}")
    print(f"C1 CLC  (ACS year {year})")
    print(f"{'─'*50}")
    print(f"Tracts:           {len(rows_out)}")
    print(f"Tracts w/ CLC:    {len(valid_clc)}")
    if valid_clc:
        sv = sorted(valid_clc)
        print(f"CLC range:        {sv[0]:.4f} – {sv[-1]:.4f}")
        print(f"CLC median:       {sv[len(sv)//2]:.4f}")
        print(f"CLC mean:         {sum(sv)/len(sv):.4f}")
        print(f"CLC > 1.0:        {sum(1 for v in sv if v > 1.0)}")

    print(f"\n{'Metro':<22}  {'Tracts':>6}  {'Props':>6}  {'Units':>8}  {'AvgCLC':>8}")
    print("─" * 58)
    metro_stats: dict = defaultdict(lambda: {"tracts": 0, "props": 0, "units": 0.0, "clcs": []})
    for r in rows_out:
        m = r["metro"]
        metro_stats[m]["tracts"] += 1
        metro_stats[m]["props"]  += int(r["num_reit_properties"] or 0)
        metro_stats[m]["units"]  += float(r["reit_units_total"] or 0)
        if r["clc"]:
            metro_stats[m]["clcs"].append(float(r["clc"]))
    for metro in sorted(metro_stats):
        ms  = metro_stats[metro]
        avg = sum(ms["clcs"]) / len(ms["clcs"]) if ms["clcs"] else float("nan")
        print(f"  {metro:<20}  {ms['tracts']:>6}  {ms['props']:>6}  "
              f"{int(ms['units']):>8,}  {avg:>8.4f}")

    print(f"\nWrote {len(rows_out)} rows → {out_file.name}")


if __name__ == "__main__":
    main()
